### ISSUE TITLE
Не вижу ссылки для скачивания app-order.jar

### ISSUE THREAD

**Issue by SakharovEugeniy** [SakharovEugeniy/homeworkAT2#1]
## Домашнее задание к занятию «2.1. Тестирование веб-интерфейсов»
Прошу указать в каком месте домашнего задания [https://github.com/netology-code/aqa-homeworks/blob/master/web/README.md](https://github.com/netology-code/aqa-homeworks/blob/master/web/README.md) найти ссылку на скачивание файла **app-order.jar** для последующей установки локальной страницы.

**Comment by ArRomanov** [comment]
https://github.com/netology-code/aqa-homeworks/blob/master/web/app-order.jar

Вам необходимо клонировать репозиторий на компьютер и после этого вы увидите все необходимые файлы
