### ISSUE TITLE
Не видит аннотацию @Test и последующие операторы

### ISSUE THREAD

**Issue by SakharovEugeniy** [SakharovEugeniy/homeworkAT2#2]
## Домашнее задание к занятию «2.1. Тестирование веб-интерфейсов»
При попытке создания автотеста столкнулся с проблемой что IDEA не распознаёт аннотацию @Test хотя build.gradle собран.  Комит прилагается.
cd83c571d976c4085af2c37ec1b9df3ccb305ffc

**Comment by coursar** [comment]
Нужно смотреть логи:
```
> Task :compileTestJava
/src/test/java/CallbackTest.java:5: error: invalid method declaration; return type required
    voidshouldSubmitRequest(){
    ^
1 error

> Task :compileTestJava FAILED

FAILURE: Build failed with an exception.
```

Потому что по правилам Java вы обязаны определять тип возвращаемого значения у метода

Должно быть:
```java
public class CallbackTest {
    @Test
    void shouldSubmitRequest(){
        open("http://localhost:9999");
    }
}
```

У вас же:
```java
public class CallbackTest {
    @Test
    voidshouldSubmitRequest(){
        open("http://localhost:9999");
    }
}
```

IDEA вам активно всё подчёркивает красным:
<img width="583" alt="Снимок экрана 2019-11-29 в 12 04 10" src="https://user-images.githubusercontent.com/3601892/69857209-7b3ec500-12a0-11ea-8d82-aab22f4c153d.png">

Нужно быть внимательнее к сообщениям среды, своему коду и логам.

**Comment by SakharovEugeniy** [comment]
Прошу извинить за невнимательность по поводу void. К сожалению оператор open и SelenideElementform продолжают гореть красным и предлагают создание статического метода
```import org.junit.jupiter.api.Test;

public class CallbackTest {
    @Test
    void shouldSubmitRequest(){
        open("http://localhost:9999");
        SelenideElementform=$("[data-test-id=callback-form]");
    }
}```
