### ISSUE TITLE
Падает тест 

### ISSUE THREAD

**Issue by SakharovEugeniy** [SakharovEugeniy/homeworkAT2#3]
> ## Домашнее задание к занятию «2.1. Тестирование веб-интерфейсов»
> Прошу помочь понять почему падает тест при запуске. 
Сообщение в логе :
[test.zip](https://github.com/SakharovEugeniy/homeworkAT2/files/3905348/test.zip)
и комит 79bedffa54df95a9dffe70d96da5aa187b5d9f51 прилагаются.

**Comment by ArRomanov** [comment]
Вы взяли код теста из примера и пытаетесь запустить этот код для приложения из домашки. Чего вы ожидали в таком случае? Приложение из примера + код из примера, приложение из домашки + код, написанный вами. Больше никак.

И по поводу оформления:
1. Прикладывайте скрины ошибки или файл с логом прямо в ишью, потому что операции по скачиванию и разворачиванию архива занимают больше времени.
2. Описывайте свои действия в ишью и давайте максимальную информацию. Зная, что вы взяли приложение из домашки, а код из презентации мне бы не пришлось клонировать ваш проект и запускать его, а сразу мог написать вам ответ.
