### ISSUE TITLE
Прошу помощи в выявлении неправильного css селектора

### ISSUE THREAD

**Issue by SakharovEugeniy** [SakharovEugeniy/homeworkAT2#5]
При запуске теста void shouldSubmitRequest() получаю заваленный тест со следующим логом https://pastebin.com/9H3ZFsWN . CSS селектор 15-ой строки проверил, несоответствия не нашёл. Прошу подсказать.

**Comment by ArRomanov** [comment]
`[data-test-id=span.button__text]`
Это селектор не валидный, то есть вообще не по правилам css. Посмотрите внимательнее, какое значение у атрибута data-test-id. А вообще, это не тот элемент, по которому нужно кликать для отправки формы.

Также обратите внимание на последнее действие, там тоже неправильный селектор. Если хотите указывать значение атрибута class, то нужно указывать полное значение. И вообще, у искомого вами элемента есть уникальный более удобный атрибут
