### ISSUE TITLE
Вопрос по окончанию работы

### ISSUE THREAD

**Issue by SakharovEugeniy** [SakharovEugeniy/homeworkAT2#6]
## Здравствуйте Артём.
Наконец то удалось завершить домашнее задание [2.1](https://github.com/netology-code/aqa-homeworks/blob/master/web/README.md). Тест проходит, CI успешно подключён. Но остались непонятными два момента:
* Неясно формирование файла .appveyor.yml. Например если я приду работать в компанию и меня попросят прикрутить CI то как его прописывать. Если это отдельная длинная тема то можете так и указать.
* Не понятны правила указания элементов css в коде программы т.е. как правильно найти селектор элемента на странице я разобрался, но вот по каким правилам он записывается в коде не понятно (у некоторых элементов очень длинные селекторы с указанием классов элементов родителей).

*P.S. к сожалению текущий уровень английского недостаточен для прочтения исходников на английском, и буду признателен за русскоязычный материал.*

**Comment by ArRomanov** [comment]
1. Разные системы ci настраиваются по разному. Вот с appveyor вообще ни разу не сталкивался. Поэтому, скорее всего, придется разбираться самостоятельно или с коллегами. Самая часто встречающаяся ci - jenkins и вы можете найти много статей и пособий по работе с данным инструментом
http://automation-remarks.com/tri-sposoba-podniat-jenkins-ci-dlia-vashikh-avtotiestov/
https://victorz.ru/20181009775
2. По поводу локаторов не совсем понял. Обычно вы подбираете локатор и просто переносите его в код в том же виде, ничего менять не нужно
http://prostoitblog.ru/kak-sostavlyat-xpath-i-css-selektoryi/
https://kreisfahrer.gitbooks.io/selenium-webdriver/webdriver_api_slozhnie_vzaimodeistviya/lokatori_css,_xpath,_jquery.html
https://www.software-testing.ru/library/testing/testing-automation/3129-web-element-locators-for-test-automation
